services:

  rasa:
    container_name: rasa_server
    image: rasa/rasa:3.6.20-full
    user: "1000:1000"
    ports:
      - "5005:5005"
    volumes:
        - ./:/app:rw
        - ./models:/app/models
        - ./.rasa:/app/.rasa
    command:
        - run
        - --enable-api
        - --cors
        - "*"
        - --debug
    depends_on:
      - action_server

  action_server:
      image: rasa/rasa-sdk:3.1.0
      ports:
        - "5055:5055"
      volumes:
        - ./actions:/app/actions

